### ISSUE TITLE
Preparation meeting, week 0

### ISSUE THREAD

**Issue by pmhsfelix** [i-on-project/meta#6]
Preparation meeting, week 0

Agenda
- Group organisation and supervisors
- Weekly calendar
- Ways of working

Tasks
- [x] Create calendar
- [] Define the ways of working document
- [] Create repos for each project

**Comment by jmchamica** [comment]
### TODO until next meeting
* Analyze the **i-on** system's **Model**
    - types
    - properties
    - relations
* Picking the right tools for the core project
    - Spring MVC vs WebFlux
    - R2DBC vs JDBC-based vs Spring Data
    - or further alternatives
* Suggest use cases for the various services
